name: Build APK

on:
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest


    steps:

      # 拉取 h5-apk-builder（你的 Vue3 dist）
      - name: Checkout builder
        uses: actions/checkout@v4


      # 拉取 Android 壳模板
      - name: Checkout android template
        uses: actions/checkout@v4
        with:
          repository: wj886104/h5-apk-template
          path: android


      # 替换 dist
      - name: Copy Vue dist
        run: |
          rm -rf android/app/src/main/assets/dist
          mkdir -p android/app/src/main/assets/dist
          cp -r dist/* android/app/src/main/assets/dist/


      # Java环境
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "17"


      # Android环境
      - name: Setup Android
        uses: android-actions/setup-android@v3


      # 编译APK
      - name: Build APK
        working-directory: android
        run: |
          chmod +x gradlew
          ./gradlew assembleRelease


      # 保存APK
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: apk-release
          path: android/app/build/outputs/apk/release/*.apk
